version: '3.8'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db_ums
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
